POST http://localhost:3000/contact HTTP/1.1
content-type: application/json

{
    "email": "some-email",
    "firstName": "some-firstname",
    "surName":"some-surname"
}

###

GET  http://localhost:3000/contact/65cc88e9e2cc21eb157ae21b HTTP/1.1
content-type: application/json