POST http://localhost:3000/contact HTTP/1.1
content-type: application/json

{
    "email": "some-email",
    "firstName": "some-firstname",
    "surName":"some-surname"
}

###

GET  http://localhost:3000/contact/65cc89ce92e74ba1f927e346 HTTP/1.1
content-type: application/json