POST http://localhost:3000/contact HTTP/1.1
content-type: application/json

{
    "email": "some-email",
    "firstName": "some-firstname",
    "surName":"some-surname"
}

###

GET  http://localhost:3000/contact/65cc6188a3aa840562ff4c9a HTTP/1.1
content-type: application/json